# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-13 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytweet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('tweet', models.ManyToManyField(to='mytweet.Tweets')),
            ],
            options={
                'verbose_name_plural': 'HashTags',
            },
        ),
    ]
