# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vspkdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCode',
            fields=[
                ('globalcode', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Код субъекта',
            },
        ),
    ]
