# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vspkdata', '0002_globalcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'Адрес субъекта',
            },
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Имя субъекта'},
        ),
        migrations.AddField(
            model_name='person',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vspkdata.GlobalCode'),
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vspkdata.Address'),
        ),
    ]
