# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vspkdata', '0003_auto_20161103_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('activity', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name_plural': 'Виды деятельности',
                'verbose_name': 'Вид деятельности',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=400)),
                ('short_name', models.CharField(max_length=200, null=True)),
                ('share_capital', models.DecimalField(decimal_places=2, default=0, max_digits=17)),
                ('date_of_registration', models.DateField()),
                ('correction', models.DateField()),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vspkdata.Activity')),
            ],
            options={
                'verbose_name_plural': 'Предприятия',
                'verbose_name': 'Предприятие',
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('appointment', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Руководители',
                'verbose_name': 'Руководитель',
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес субъекта', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='globalcode',
            options={'verbose_name': 'Код субъекта', 'verbose_name_plural': 'Коды'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Физлицо', 'verbose_name_plural': 'Физлица'},
        ),
        migrations.AddField(
            model_name='principal',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vspkdata.GlobalCode'),
        ),
        migrations.AddField(
            model_name='entity',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vspkdata.Address'),
        ),
        migrations.AddField(
            model_name='entity',
            name='code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vspkdata.GlobalCode'),
        ),
        migrations.AddField(
            model_name='entity',
            name='principal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vspkdata.Principal'),
        ),
    ]
