# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vspkdata', '0004_auto_20161108_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vspkdata.Principal'),
        ),
    ]
