# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vspkdata', '0005_auto_20161108_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='principal',
        ),
        migrations.AddField(
            model_name='principal',
            name='entity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vspkdata.Entity'),
        ),
    ]
