# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-10 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vspkdata', '0006_auto_20161108_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(db_index=True, max_length=12, unique=True, verbose_name='username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователь',
            },
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['code'], 'verbose_name': 'Вид деятельности', 'verbose_name_plural': 'Виды деятельности'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['code'], 'verbose_name': 'Предприятие', 'verbose_name_plural': 'Предприятия'},
        ),
        migrations.AlterModelOptions(
            name='globalcode',
            options={'ordering': ['globalcode'], 'verbose_name': 'Код субъекта', 'verbose_name_plural': 'Коды'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'code'], 'verbose_name': 'Физлицо', 'verbose_name_plural': 'Физлица'},
        ),
        migrations.AlterModelOptions(
            name='principal',
            options={'ordering': ['entity', 'appointment'], 'verbose_name': 'Руководитель', 'verbose_name_plural': 'Руководители'},
        ),
    ]
